from enum import Enum

class State(str, Enum):
    
    def __str__(self):
        return str(self.value)

    STATE_TOSTART = 'STATE_TO_START'
    STATE_WAIT_ACTION = 'STATE_WAIT_ACTION'
    STATE_WAIT_SIMILAR_IMAGE = 'STATE_WAIT_SIMILAR'
    STATE_WAIT_STYLE_BASE = 'STATE_WAIT_STYLE_BASE'
    STATE_WAIT_STYLE_STYLE = 'STATE_WAIT_STYLE_STYLE'
    STATE_CHOOSE_SIMILARITY = 'STATE_CHOOSE_SIMILARITY'
    STATE_QUALITY_ASK_CONTINUE = 'STATE_QUALITY_ASK_CONTINUE'
    STATE_CHOOSE_FILTER = 'STATE_CHOOSE_FILTER'
    STATE_WAIT_FOR_APPLY_FILTER = 'STATE_WAIT_APPLYING_FILTER'
    STATE_WAIT_FOR_IMAGE_GIF = 'STATE_WAIT_FOR_IMAGE_GIF'